/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DangNhapController;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Toolkit;
import java.awt.Color;
import java.awt.Image;

import javax.swing.JLabel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Font;

/**
 *
 * @author MY PC
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public static String vaiTroQuanLy ="";
    DangNhapController loginControl;
    
    public LoginView() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(LoginView.class.getResource("/img/apartment_13889041-min.png")));
        initComponents();
        setResizable(false);
        
        loginControl = new DangNhapController(this);
        
        this.setTitle("Đăng nhập");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        matkhau = new javax.swing.JPasswordField();
        dangNhapText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel1.setForeground(new Color(0, 102, 153));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel2.setForeground(new Color(0, 102, 153));
        dangnhap = new javax.swing.JButton();
        dangnhap.setBorderPainted(false);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setForeground(new Color(0, 102, 153));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(230, 242, 255));

        jLabel1.setText("Tên đăng nhập: ");

        jLabel2.setText("Mật khẩu:");

        dangnhap.setText("Đăng nhập");
        dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangnhapActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("ĐĂNG NHẬP");
        
        
        
        
        
        
        lblNewLabel = new JLabel();
     // Load the image from the resource path
        ImageIcon originalIcon2 = new ImageIcon(getClass().getResource("/img/bluebackground.png"));

        // Resize the image to fit within the JLabel's fixed size
        Image image2 = originalIcon2.getImage();
        Image resizedImage2 = image2.getScaledInstance(370, 100, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon2 = new ImageIcon(resizedImage2);

        // Create a JLabel and set the ImageIcon as its icon
        JLabel lblNewLabel = new JLabel(resizedIcon2);
        
        
        
        
        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        			.addContainerGap(242, Short.MAX_VALUE)
        			.addComponent(dangnhap)
        			.addGap(53))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(72)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(matkhau)
        				.addComponent(dangNhapText, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(72, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(29)
        			.addComponent(jLabel3)
        			.addContainerGap(241, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(dangNhapText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(matkhau, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2))
        			.addGap(18)
        			.addComponent(dangnhap)
        			.addGap(30))
        );
        jPanel1.setLayout(jPanel1Layout);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 371, GroupLayout.PREFERRED_SIZE)
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangnhapActionPerformed
        String userName = this.dangNhapText.getText();
        String password = String.valueOf(this.matkhau.getPassword());
            if (!this.loginControl.login(userName, password).equals("")) {
                dispose();
                vaiTroQuanLy = this.loginControl.login(userName, password);
                MainView mainview = new MainView(vaiTroQuanLy);
            } else {
                JOptionPane.showMessageDialog(this, "Sai thông tin đăng nhập", "Warning", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_dangnhapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dangNhapText;
    private javax.swing.JButton dangnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField matkhau;
    private JLabel lblNewLabel;
    // End of variables declaration//GEN-END:variables
}
